/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#dfe4e0",
        "primary": "#f0ffee",
        "surface-container-lowest": "#0a0f0d",
        "pitch-green-dark": "#051A10",
        "inverse-primary": "#006d35",
        "outline-variant": "#3b4b3d",
        "error": "#ffb4ab",
        "on-primary-fixed": "#00210c",
        "surface-container-high": "#262b29",
        "inverse-surface": "#dfe4e0",
        "on-tertiary-container": "#736000",
        "surface-container-highest": "#313633",
        "surface-elevated": "#141C19",
        "secondary-fixed-dim": "#00daf8",
        "surface-container": "#1c211e",
        "on-surface": "#dfe4e0",
        "on-error": "#690005",
        "on-surface-variant": "#b9cbb9",
        "text-muted": "#8E9B96",
        "primary-fixed-dim": "#00e476",
        "on-secondary-fixed-variant": "#004e5a",
        "on-secondary-container": "#005f6d",
        "tertiary-fixed-dim": "#e9c400",
        "on-primary-container": "#007137",
        "danger-red": "#FF4B4B",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#005227",
        "on-primary": "#003919",
        "inverse-on-surface": "#2c322f",
        "on-tertiary-fixed-variant": "#544600",
        "primary-container": "#00ff85",
        "surface-bright": "#353a38",
        "surface-container-low": "#181d1a",
        "tertiary-container": "#ffdc49",
        "on-tertiary": "#3a3000",
        "surface-tint": "#00e476",
        "stadium-glow": "#1A2E25",
        "secondary-fixed": "#a5eeff",
        "tertiary": "#fffaf5",
        "surface-variant": "#313633",
        "error-container": "#93000a",
        "primary-fixed": "#61ff97",
        "outline": "#849584",
        "on-secondary-fixed": "#001f25",
        "secondary": "#b9f1ff",
        "surface": "#0f1412",
        "surface-dim": "#0f1412",
        "on-tertiary-fixed": "#221b00",
        "secondary-container": "#00e0ff",
        "tertiary-fixed": "#ffe16d",
        "on-secondary": "#00363f",
        "background": "#0f1412",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "max-width": "1440px",
        "base": "8px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "gutter": "24px",
      },
      maxWidth: {
        "max-width": "1440px",
      },
      fontFamily: {
        "stat-lg": ["JetBrains Mono", "monospace"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "stat-sm": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "stat-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "stat-sm": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
      animation: {
        "float-slow": "float 6s ease-in-out infinite",
        "float-slow-reverse": "float 8s ease-in-out infinite reverse",
      },
    },
  },
  plugins: [],
}
